<?php

namespace App\Http\Controllers\V1\Common;

use App\Cache\User\OauthCache;
use App\Http\Controllers\BaseController;
use App\Http\Requests\Common\SmsRequest;
use App\Http\Requests\User\Member\MemberRequest;
use App\Http\Services\Common\EmailService;
use App\Http\Services\Common\SmsChannelSwitcher;
use App\Http\Services\Common\SmsService;
use App\Http\Services\User\UserService;
use Illuminate\Http\JsonResponse;
use Log;

class EmailController extends BaseController
{
    /**
     * 获取短信验证码
     *
     * @param MemberRequest $request
     * @param UserService $service
     * @return JsonResponse
     * @author fable
     */
    public function sendEmail(SmsRequest $request): JsonResponse
    {
        try {
            $mobile = $request->get('email');
            $message_type = $request->get('message_type');
            // 重新获取删除之前的错误次数
            OauthCache::delCodeErrorTimes($mobile, $message_type);
            // 初始化 SmsChannelSwitcher

            $smsChannelSwitcher = new SmsChannelSwitcher($mobile, $message_type);

            // 获取通道和验证码
            list($channel, $msg_code) = $smsChannelSwitcher->getChannelAndCode();

            // 发送短信验证码
            $subject = '您的验证码';
            $content = "尊敬的用户，您的验证码为：{$msg_code}。";
            $result = (new EmailService)->sendMail(
                $request->get('email'),
                $subject,
                'emails.test', // 假设有一个邮件视图 `resources/views/emails/test.blade.php`
                ['name' => $content]
            );
            if (!$result) {
                throw new \Exception(trans('codes.10023'), 10023);
            }

//            $smsChannelSwitcher->updateUsedChannels($channel);
            return $this->success(msg: trans('codes.10020'));
        } catch (\Exception $e) {
            return $this->fail([], $e->getMessage());
        } finally {
            if (isset($message_code)) {
                $request->offsetSet('message_code', $message_code);
            }
            Log::info(
                '获取验证码(' . $request->get('message_type') . ')',
                $this->logBody($e ?? null, $request)
            );
            $request->offsetUnset('message_code');
        }
    }


    public function checkCodes(SmsRequest $request,SmsService $service): JsonResponse
    {
        $mobile = $request->get('email');
        $message_code = $request->get('code');
        $type = $request->get('message_type');
        if ($service->checkCode($mobile, $message_code, $type)) {
            return $this->success(); // TODO: Change the autogenerated stub
        }
        return $this->fail([], trans('codes.10022'));
    }
}
